name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (from .nvmrc) + npm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Print tool versions
        run: |
          node -v
          npm -v

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      # ---- Unit tests (exclude rtc/webrtc/dtls via run-tests-ci.mjs)
      - name: Unit tests
        run: npm run test:spec

      # ---- RTC tests (memory signaler) via run-webrtc.mjs
      - name: RTC tests
        env:
          CI_ALLOW_INTEGRATION: "1"
          TEST_SIGNAL_MODE: "memory"
          # Optional: extend the safety valve if CI is slow
          WRTC_TEST_MAX_MS: "45000"
        run: npm run test:ci:webrtc

      - name: Pack dry-run (workspace)
        run: npm run pack:dry
